### ISSUE TITLE
add other iiwa models in urdf

### ISSUE THREAD

**Issue by mcbed** [ICube-Robotics/iiwa_ros2#5]
The currently available model of the iiwa robot is the iiwa 14 R820 with pneumatic touch flange. 
**Feature**: add models and urdf variants for iiwa 7, med series and different flanges.

**Comment by MightyMirko** [comment]
Hi, 

currently i'm trying to add the iiwa 7 with electrical media flange: 

This is my urdf.xacro: EDIT: Uploaded as gist and correcting it 
https://gist.github.com/MightyMirko/58fa382c733f8555cbf86055a3ad49f4


I did change the iiwa.config.xacro to that file but it seems there is an error:


```
hkatp-admin@v100-u20-foxy-mirko:~/Dokumente/fri_ros2-ws$ source install/setup.bash && ros2 launch iiwa_bringup iiwa.launch.py --debug 
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/hkatp-admin/.ros/log/2023-02-27-19-45-57-654021-v100-u20-foxy-mirko-332661
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f2cf42fd1c0>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7f2cf42fd1c0>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7f2cf42e6ca0>'
Executing <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure('executed command failed. Command: /opt/ros/foxy/bin/xacro /home/hkatp-admin/Dokumente/fri_ros2-ws/install/iiwa_description/share/iiwa_description/config/iiwa.config.xacro prefix:="" use_sim:=false use_fake_hardware:=true robot_ip:=192.170.10.2 robot_port:=30200 initial_positions_file:=initial_positions.yaml command_interface:=position') created at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:314> took 0.142 seconds
[DEBUG] [launch.launch_context]: emitting event: 'launch.events.Shutdown'
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure('executed command failed. Command: /opt/ros/foxy/bin/xacro /home/hkatp-admin/Dokumente/fri_ros2-ws/install/iiwa_description/share/iiwa_description/config/iiwa.config.xacro prefix:="" use_sim:=false use_fake_hardware:=true robot_ip:=192.170.10.2 robot_port:=30200 initial_positions_file:=initial_positions.yaml command_interface:=position') created at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:314>
source_traceback: Object created at (most recent call last):
  File "/opt/ros/foxy/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.12', 'console_scripts', 'ros2')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2launch/command/launch.py", line 151, in main
    return launch_a_launch_file(
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2launch/api/api.py", line 167, in launch_a_launch_file
    ret = launch_service.run()
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 360, in run
    return loop.run_until_complete(run_async_task)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 314, in run_async
    process_one_event_task = this_loop.create_task(self._process_one_event())
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 1 more time]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 444, in execute
    self._perform_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 399, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 164, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 71, in evaluate_parameter_dict
    evaluated_value = perform_substitutions(context, list(value))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 232, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/substitutions/command.py", line 116, in perform
    raise SubstitutionFailure(f'executed command failed. Command: {command_str}')
launch.substitutions.substitution_failure.SubstitutionFailure: executed command failed. Command: /opt/ros/foxy/bin/xacro /home/hkatp-admin/Dokumente/fri_ros2-ws/install/iiwa_description/share/iiwa_description/config/iiwa.config.xacro prefix:="" use_sim:=false use_fake_hardware:=true robot_ip:=192.170.10.2 robot_port:=30200 initial_positions_file:=initial_positions.yaml command_interface:=position
[DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f2cf42e6ac0>'
[DEBUG] [launch]: processing event: '<launch.events.shutdown.Shutdown object at 0x7f2cf42e6ac0>' ✓ '<launch.event_handlers.on_shutdown.OnShutdown object at 0x7f2cf42e6fd0>'

```


Can someone look at it and point at my error? 
I've built and sourced of course

**Comment by MightyMirko** [comment]
Got it :-) the robot macro name was wrong

https://gist.github.com/MightyMirko/58fa382c733f8555cbf86055a3ad49f4
